import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type LauncherLocale = 'en' | 'tr' | 'de' | 'fr' | 'es';
type Variables = Record<string, string | number>;

const en = {
  'language.label': 'Language',
  'language.en': 'English',
  'language.tr': 'Türkçe',
  'language.de': 'Deutsch',
  'language.fr': 'Français',
  'language.es': 'Español',
  'language.launcherLanguage': 'Launcher language',
  'language.savedHelp': 'Applied immediately and remembered on this device.',
  'common.close': 'Close',
  'common.clear': 'Clear',
  'common.required': 'Required',
  'common.recommended': 'Recommended',
  'common.ready': 'Ready',
  'common.offline': 'Offline',
  'common.launcher': 'Launcher',
  'common.managedApp': 'Managed App',
  'common.checkAgain': 'Check Again',
  'common.checking': 'Checking...',
  'common.detected': 'Detected: {path}',
  'qr.code': 'QR Code',
  'qr.scan': 'Scan to connect',
  'status.launcherReady': 'Launcher ready.',
  'status.browserPreview': 'Browser preview — Tauri commands are simulated.',
  'status.loadingEnvironment': 'Loading environment…',
  'status.noProfile': 'No profile is available.',
  'status.apiPortRange': 'API port must be between 1024 and 65535.',
  'status.uiPortRange': 'UI port must be between 1024 and 65535.',
  'status.localPortRange': 'Local port must be between 1024 and 65535.',
  'status.portsDifferent': 'API and UI ports must be different.',
  'status.portsAvailable': 'Ports are available.',
  'status.localPortValid': 'Local port is valid.',
  'status.previewPortsValid': 'Ports look valid in browser preview.',
  'status.existingInstance': 'HomeInventory is already running on the selected ports. Open the existing session instead of starting a duplicate.',
  'status.apiPortBusy': 'API port {port} is busy. Suggested: {suggested}.',
  'status.uiPortBusy': 'UI port {port} is busy. Suggested: {suggested}.',
  'status.bothPortsBusy': 'Ports {backend} and {frontend} are busy. Suggested: {suggestedBackend}/{suggestedFrontend}.',
  'status.networkReady': 'Network address is ready. If another device cannot connect, allow HomeInventory or Node.js through Windows Firewall for private networks.',
  'status.lanUiBlocked': 'The app UI is not reachable through the LAN IP. Check Windows Firewall and host binding.',
  'status.lanApiBlocked': 'The app UI is reachable, but the API is not reachable through the LAN IP.',
  'status.lanBlocked': 'LAN check failed. Allow HomeInventory or Node.js through Windows Firewall for private networks, then restart the app.',
  'status.checkingPorts': 'Checking local ports before launch…',
  'status.randomLocalPort': 'Selected available local port {port}.',
  'status.randomPorts': 'Selected available API/UI ports {backend}/{frontend}.',
  'status.defaultPortsBusy': 'Default ports were busy. Launching on {backend}/{frontend}.',
  'status.startPreview': 'Starting {name}: simulated in browser mode.',
  'status.stopPreview': 'Stopped active profile: simulated in browser mode.',
  'status.setupStopped': 'HomeInventory stopped before it finished starting. Open Developer Tools for logs.',
  'status.folderPickerDesktop': 'Folder picker is available in the desktop launcher.',
  'status.folderSelected': 'Install folder selected.',
  'status.folderCleared': 'Install folder cleared.',
  'status.pathPickerDesktop': 'Path picker is available in the desktop launcher.',
  'status.pathUpdated': 'Path updated. Tool detection will refresh automatically.',
  'status.pathEmpty': '{label} path is empty.',
  'status.folderRevealDesktop': 'Folder reveal is available in the desktop launcher.',
  'status.pathOpened': '{label} opened.',
  'status.nodeOverridesCleared': 'Node/npm overrides cleared. Auto-detect is active.',
  'status.backupPreview': 'Backup created for {name}: simulated in browser mode.',
  'setup.subtitle': 'Your private household registry',
  'setup.localFirst': 'Local-first',
  'setup.waiting': 'Waiting to initialize…',
  'setup.nodeRequired': 'Node.js is required.',
  'setup.preparingFiles': 'Preparing application files…',
  'setup.installing': 'Installing dependencies and preparing the app…',
  'setup.failed': 'Setup stopped after an error. Choose another install folder, then try again.',
  'setup.elapsedBundled': 'Elapsed {elapsed}. Preparing bundled app files and runtime.',
  'setup.elapsedInstall': 'Elapsed {elapsed}. First install can take a few minutes depending on npm and network speed.',
  'setup.runtimeNotReady': 'Bundled runtime not ready',
  'setup.nodeNotFound': 'Node.js not found',
  'setup.runtimeHelp': 'Launch HomeInventory Local to prepare the runtime included with the Microsoft Store package.',
  'setup.nodeHelpPrefix': 'Download and install from',
  'setup.nodeHelpSuffix': 'to continue.',
  'setup.checkingLocalPorts': 'Checking local ports…',
  'setup.launchLocal': 'Launch HomeInventory Local',
  'setup.chooseInstallFolder': 'Choose Install Folder',
  'setup.installLaunch': 'Install & Launch',
  'setup.openRunning': 'Open Running HomeInventory',
  'setup.launchOn': 'Launch on {backend}/{frontend}',
  'setup.initializeLaunch': 'Initialize & Launch',
  'setup.developerTools': 'Developer Tools',
  'setup.hideConsole': 'Hide console',
  'setup.systemConsole': 'System console',
  'setup.connectingRegistry': 'Connecting to your registry',
  'setup.startingServices': 'Starting services…',
  'setup.launching': 'Launching…',
  'setup.connectingDatabase': 'Connecting to database…',
  'setup.servicesStopped': 'Services are stopped',
  'setup.readyToLaunch': 'Ready to launch',
  'setup.restartLocal': 'Restart HomeInventory Local',
  'setup.restart': 'Restart HomeInventory',
  'setup.launch': 'Launch HomeInventory',
  'setup.checkingUpdates': 'Checking for updates…',
  'setup.updateApp': 'Update App to v{version}',
  'setup.storePreparation': 'HomeInventory Local will prepare its bundled app files and local runtime from the Microsoft Store package.',
  'setup.chooseFolderHelp': 'Choose an empty install folder or an existing HomeInventory folder.',
  'setup.emptyFolderSelected': 'Empty install folder selected. HomeInventory will be downloaded and installed here.',
  'setup.invalidFolder': 'This folder is not empty and is not a HomeInventory install folder.',
  'update.kicker': 'Updates',
  'update.syncPaused': 'Managed app sync paused',
  'update.inProgress': 'Update in progress',
  'update.checking': 'Checking updates...',
  'update.availableBeforeLaunch': 'Update available before launch',
  'update.checkedBeforeLaunch': 'Checked before launch',
  'update.checkBeforeLaunch': 'Check updates before launch',
  'update.previousAvailable': 'The previous version remains available. Retry when you are ready.',
  'update.lookingForReleases': 'Looking for signed launcher and app releases.',
  'update.nodeUpgradeBeforeInstall': 'Node.js must be upgraded before this update can be installed.',
  'update.installBeforeStart': 'Install the verified update before starting HomeInventory.',
  'update.noneAvailable': 'No update is available right now.',
  'update.verifyBeforeStart': 'Verify releases, signatures, and requirements before starting services.',
  'update.retrySync': 'Retry Sync',
  'update.updateFirst': 'Update First',
  'update.checkUpdates': 'Check Updates',
  'update.checkForUpdates': 'Check for updates',
  'update.upToDateNotice': 'Your software is up to date.',
  'update.checkFirst': 'Please check for updates before starting the update.',
  'update.noInstallAvailable': 'Your software is up to date. No update is available to install.',
  'update.initializing': 'Initializing update orchestration...',
  'update.backingUp': 'Creating database and uploads backup...',
  'update.downloading': 'Downloading release archive...',
  'update.installing': 'Running npm ci dependency install...',
  'update.complete': 'Update complete!',
  'update.stateStarting': 'Starting',
  'update.stateBackingUp': 'Backing Up',
  'update.stateDownloading': 'Downloading',
  'update.stateInstalling': 'Installing',
  'update.stateCompleted': 'Completed',
  'update.stateRollback': 'Rolling Back',
  'update.stateRollbackComplete': 'Rollback Complete',
  'update.stateFailed': 'Failed',
  'update.manage': 'Manage and check for software updates.',
  'update.checkingForUpdates': 'Checking for updates...',
  'update.toVersion': '(Update to v{version})',
  'update.nodeRequired': 'Node.js Upgrade Required',
  'update.nodeRequiredBody': 'The latest app version requires Node.js v{version} or higher. Please upgrade your Node.js runtime to proceed with the update.',
  'update.appReleaseNotes': 'App Release Notes',
  'update.launcherReleaseNotes': 'Launcher Release Notes',
  'update.softwareCurrent': 'Your software is up to date',
  'update.latestVersions': 'You are running the latest version of HomeInventory and the desktop launcher.',
  'update.updateHomeInventory': 'Update HomeInventory',
  'update.checkBeforeInstalling': 'Check updates before installing',
  'update.checkExplanation': 'Before running the updater, the launcher should verify the latest release, signatures, required Node.js version, and available app or launcher updates.',
  'update.temporarilyUnavailable': 'Update information is temporarily unavailable',
  'running.status': 'Running',
  'running.localAccess': 'Local access',
  'running.ready': 'Your inventory is ready.',
  'running.help': 'Open it on this device, or scan the code from another device on the same network.',
  'running.standardLan': 'Standard LAN access · no certificate setup',
  'running.lanPending': 'LAN status is checked after the services bind to the network.',
  'running.openBrowser': 'Open in browser',
  'running.openApp': 'Open app',
  'running.port': 'Port {port}',
  'running.ports': 'Ports {backend}/{frontend}',
  'running.controls': 'App controls',
  'running.settings': 'Launcher settings',
  'running.stop': 'Stop local services',
  'running.active': '{name} is running.',
  'https.setupLabel': 'Secure mobile camera setup',
  'https.title': 'Secure mobile camera access',
  'https.subtitle': 'Optional · offline · no domain or external service',
  'https.installTitle': '1 · Install the certificate',
  'https.choosePlatform': 'Choose iPhone / iPad or Android.',
  'https.ios': 'iPhone / iPad',
  'https.iosHelp': 'Install the profile, then enable full trust under Settings → General → About → Certificate Trust Settings.',
  'https.android': 'Android',
  'https.downloadPrefix': 'The QR downloads',
  'https.downloadSuffix': 'the public CA certificate generated for this launcher. It contains no private key or HomeInventory data.',
  'https.phoneBrand': 'Phone brand',
  'https.scanDownload': 'Scan the QR to download the certificate.',
  'https.typicalPath': 'Typical path:',
  'https.finishInstall': 'Select the downloaded file, finish installation, then scan',
  'https.openSecureApp': '2 · Open secure app',
  'https.menuVariation': 'Menu names can vary slightly by Android version.',
  'https.secureHelp': 'The browser must open this address without a certificate warning before camera permission can work.',
  'https.linksExpire': 'Enrollment links expire after 10 minutes. The CA private key never leaves this computer.',
  'https.refreshLinks': 'Refresh setup links',
  'https.disable': 'Disable HTTPS',
  'https.rotate': 'Rotate compromised CA',
  'https.removal': 'Disabling HTTPS does not remove the trusted CA from a phone. Remove the HomeInventory profile/CA from device settings when it is no longer needed.',
  'https.optionalLabel': 'Optional secure mobile camera access',
  'https.wantCamera': 'Want to scan with a phone camera?',
  'https.oneTimeSetup': 'LAN camera access requires a one-time trusted HTTPS setup on each phone.',
  'https.enable': 'Enable secure mobile camera',
  'https.normalRemains': 'Normal HTTP access remains available and this setup is completely optional.',
  'https.startFirst': 'Start HomeInventory before enabling secure mobile camera access.',
  'https.previewEnabled': 'Secure mobile camera setup is simulated in browser preview.',
  'https.readyNotice': 'Secure mobile access is ready at {url}. Install the local CA on each phone before opening it.',
  'https.disabledNotice': 'Secure mobile access is disabled. Normal HTTP access is unchanged.',
  'https.rotateConfirm': 'Rotate the HomeInventory local CA? Every enrolled phone will stop trusting the old certificate and must install the new one.',
  'https.rotatePreview': 'Local CA rotation is simulated in browser preview.',
  'android.samsung': 'Samsung Galaxy',
  'android.pixel': 'Google Pixel / standard Android',
  'android.other': 'Other Android',
  'android.samsungPath': 'Settings → Security and privacy → More security settings → Install from device storage → CA certificate',
  'android.pixelPath': 'Settings → Security & privacy → More security settings → Encryption & credentials → Install a certificate → CA certificate',
  'android.otherPath': 'Open Settings, search for “Install certificate”, then choose CA certificate.',
  'advanced.title': 'Advanced',
  'advanced.configuration': 'Advanced Configuration',
  'advanced.whatMatters': 'What matters here',
  'advanced.emailLabel': 'Email:',
  'advanced.emailHelp': 'Resend needs both an API key and a verified sender address. A key alone can look configured but still fail delivery.',
  'advanced.adminLabel': 'Admin:',
  'advanced.adminHelp': 'Bootstrap Admin Email makes the first trusted admin predictable.',
  'advanced.networkLabel': 'Network:',
  'advanced.networkStore': 'HomeInventory Local uses one local port for the app and API.',
  'advanced.networkDesktop': 'Ports must be free locally; LAN access also depends on firewall and same Wi-Fi.',
  'advanced.emailDelivery': 'Email Delivery',
  'advanced.resendKey': 'Resend API Key',
  'advanced.resendHelp': 'Enables invitations, verification, admin mail, and password reset emails.',
  'advanced.sender': 'Verified Sender',
  'advanced.senderHelp': 'Use a sender from a verified Resend domain. For quick testing, Resend allows onboarding@resend.dev.',
  'advanced.supportEmail': 'Support Email',
  'advanced.supportHelp': 'Shown in help links and outgoing email footers.',
  'advanced.instanceAdmin': 'Instance & Admin',
  'advanced.bootstrapAdmin': 'Bootstrap Admin Email',
  'advanced.bootstrapHelp': 'The matching account receives admin privileges during first setup or sign-in.',
  'advanced.envHelp': 'Launcher writes only filled values to .env, so existing configuration is preserved.',
  'advanced.localPort': 'Local Port',
  'advanced.networkPorts': 'Network Ports',
  'advanced.apiPort': 'API Port',
  'advanced.uiPort': 'UI Port',
  'advanced.storePortHelp': 'Valid range: 1024-65535. Default: 3001. Only change if another app is using the same port.',
  'advanced.desktopPortHelp': 'Valid range: 1024-65535. Defaults: API 3001, UI 5173. Only change if another app is using the same port.',
  'advanced.randomPort': 'Find a Random Free Port',
  'advanced.randomPorts': 'Find Random Free Ports',
  'advanced.usePort': 'Use {port}',
  'advanced.usePorts': 'Use {backend}/{frontend}',
  'advanced.otherDevices': 'Access from other devices',
  'advanced.sameWifiPrefix': 'Keep devices on the',
  'advanced.sameWifi': 'same Wi-Fi network',
  'advanced.firewall': 'Allow HomeInventory or Node.js through Windows Firewall for private networks if prompted.',
  'advanced.findIp': 'Find your IP: System Settings → Wi-Fi → Details → IP Address',
  'dev.console': 'Developer Console',
  'dev.logs': 'Logs',
  'dev.backups': 'Backups',
  'dev.settings': 'Settings',
  'dev.updates': 'Updates',
  'dev.backupDescription': 'One-click backups of your local data and media.',
  'dev.backingUp': 'Backing up...',
  'dev.backupNow': 'Backup Now',
  'dev.openBackup': 'Open Backup',
  'dev.installFolder': 'Install Folder',
  'dev.installFolderHelp': 'Choose an empty folder for a new install, or an existing HomeInventory folder.',
  'dev.nodePath': 'Node Path',
  'dev.npmPath': 'npm Path',
  'dev.autoDetected': 'Auto-detected',
  'dev.nodePathHelp': 'Set this only if the launcher cannot find your Node installation.',
  'dev.npmPathHelp': 'Set this only if npm detection fails from the desktop app.',
  'dev.openFolder': 'Open Folder',
  'dev.openData': 'Open Data',
  'dev.resetDetection': 'Reset Node/npm Detection',
  'dev.stopServer': 'Stop Server',
  'dev.noLogs': 'No log entries yet.',
  'dev.choosePath': 'Choose path',
  'dev.openLocation': 'Open location',
  'dev.useDetectedPath': 'Use auto-detected path',
} as const;

export type TranslationKey = keyof typeof en;
type Dictionary = Record<TranslationKey, string>;

const tr: Dictionary = {
  ...en,
  'qr.code': 'QR Kodu', 'qr.scan': 'Bağlanmak için tarayın',
  'language.launcherLanguage': 'Launcher dili', 'language.savedHelp': 'Anında uygulanır ve bu cihazda hatırlanır.',
  'language.label': 'Dil', 'common.close': 'Kapat', 'common.clear': 'Temizle', 'common.required': 'Gerekli', 'common.recommended': 'Önerilen', 'common.ready': 'Hazır', 'common.offline': 'Çevrimdışı', 'common.checkAgain': 'Tekrar Kontrol Et', 'common.checking': 'Kontrol ediliyor...', 'common.managedApp': 'Yönetilen Uygulama', 'common.detected': 'Algılandı: {path}',
  'status.launcherReady': 'Launcher hazır.', 'status.browserPreview': 'Tarayıcı önizlemesi — Tauri komutları simüle ediliyor.', 'status.loadingEnvironment': 'Ortam yükleniyor…', 'status.noProfile': 'Kullanılabilir profil yok.', 'status.apiPortRange': 'API portu 1024 ile 65535 arasında olmalıdır.', 'status.uiPortRange': 'Arayüz portu 1024 ile 65535 arasında olmalıdır.', 'status.localPortRange': 'Yerel port 1024 ile 65535 arasında olmalıdır.', 'status.portsDifferent': 'API ve arayüz portları farklı olmalıdır.', 'status.portsAvailable': 'Portlar kullanılabilir.', 'status.localPortValid': 'Yerel port geçerli.', 'status.previewPortsValid': 'Portlar tarayıcı önizlemesinde geçerli görünüyor.', 'status.checkingPorts': 'Başlatmadan önce yerel portlar kontrol ediliyor…', 'status.randomLocalPort': 'Kullanılabilir yerel port seçildi: {port}.', 'status.randomPorts': 'Kullanılabilir API/arayüz portları seçildi: {backend}/{frontend}.', 'status.defaultPortsBusy': 'Varsayılan portlar dolu. {backend}/{frontend} üzerinde başlatılıyor.', 'status.startPreview': '{name} başlatılıyor: tarayıcı modunda simüle edildi.', 'status.stopPreview': 'Etkin profil durduruldu: tarayıcı modunda simüle edildi.', 'status.setupStopped': 'HomeInventory başlatma tamamlanmadan durdu. Günlükler için Geliştirici Araçları’nı açın.', 'status.folderPickerDesktop': 'Klasör seçici masaüstü launcher’da kullanılabilir.', 'status.folderSelected': 'Kurulum klasörü seçildi.', 'status.folderCleared': 'Kurulum klasörü temizlendi.', 'status.pathPickerDesktop': 'Yol seçici masaüstü launcher’da kullanılabilir.', 'status.pathUpdated': 'Yol güncellendi. Araç algılama otomatik yenilenecek.', 'status.pathEmpty': '{label} yolu boş.', 'status.folderRevealDesktop': 'Klasörü gösterme masaüstü launcher’da kullanılabilir.', 'status.pathOpened': '{label} açıldı.', 'status.nodeOverridesCleared': 'Node/npm geçersiz kılmaları temizlendi. Otomatik algılama etkin.', 'status.backupPreview': '{name} için yedek oluşturuldu: tarayıcı modunda simüle edildi.',
  'status.existingInstance': 'HomeInventory seçilen portlarda zaten çalışıyor. İkinci bir örnek başlatmak yerine mevcut oturumu açın.', 'status.apiPortBusy': 'API portu {port} dolu. Önerilen: {suggested}.', 'status.uiPortBusy': 'Arayüz portu {port} dolu. Önerilen: {suggested}.', 'status.bothPortsBusy': '{backend} ve {frontend} portları dolu. Önerilen: {suggestedBackend}/{suggestedFrontend}.', 'status.networkReady': 'Ağ adresi hazır. Başka bir cihaz bağlanamıyorsa özel ağlar için Windows Güvenlik Duvarı’nda HomeInventory veya Node.js’e izin verin.', 'status.lanUiBlocked': 'Uygulama arayüzüne LAN IP’si üzerinden erişilemiyor. Windows Güvenlik Duvarı’nı ve ana makine bağlamasını kontrol edin.', 'status.lanApiBlocked': 'Uygulama arayüzüne erişiliyor ancak API’ye LAN IP’si üzerinden erişilemiyor.', 'status.lanBlocked': 'LAN kontrolü başarısız. Özel ağlar için Windows Güvenlik Duvarı’nda HomeInventory veya Node.js’e izin verip uygulamayı yeniden başlatın.',
  'setup.subtitle': 'Özel ev envanteriniz', 'setup.localFirst': 'Önce yerel', 'setup.waiting': 'Başlatma bekleniyor…', 'setup.nodeRequired': 'Node.js gereklidir.', 'setup.preparingFiles': 'Uygulama dosyaları hazırlanıyor…', 'setup.installing': 'Bağımlılıklar yükleniyor ve uygulama hazırlanıyor…', 'setup.failed': 'Kurulum bir hatadan sonra durdu. Başka bir kurulum klasörü seçip tekrar deneyin.', 'setup.elapsedBundled': 'Geçen süre {elapsed}. Paketli uygulama dosyaları ve çalışma ortamı hazırlanıyor.', 'setup.elapsedInstall': 'Geçen süre {elapsed}. İlk kurulum npm ve ağ hızına göre birkaç dakika sürebilir.', 'setup.runtimeNotReady': 'Paketli çalışma ortamı hazır değil', 'setup.nodeNotFound': 'Node.js bulunamadı', 'setup.runtimeHelp': 'Microsoft Store paketindeki çalışma ortamını hazırlamak için HomeInventory Local’ı başlatın.', 'setup.nodeHelpPrefix': 'Devam etmek için', 'setup.nodeHelpSuffix': 'adresinden indirip kurun.', 'setup.checkingLocalPorts': 'Yerel portlar kontrol ediliyor…', 'setup.launchLocal': 'HomeInventory Local’ı Başlat', 'setup.chooseInstallFolder': 'Kurulum Klasörü Seç', 'setup.installLaunch': 'Kur ve Başlat', 'setup.openRunning': 'Çalışan HomeInventory’yi Aç', 'setup.launchOn': '{backend}/{frontend} Üzerinde Başlat', 'setup.initializeLaunch': 'Hazırla ve Başlat', 'setup.developerTools': 'Geliştirici Araçları', 'setup.hideConsole': 'Konsolu gizle', 'setup.systemConsole': 'Sistem konsolu', 'setup.connectingRegistry': 'Envanterinize bağlanılıyor', 'setup.startingServices': 'Servisler başlatılıyor…', 'setup.launching': 'Başlatılıyor…', 'setup.connectingDatabase': 'Veritabanına bağlanılıyor…', 'setup.servicesStopped': 'Servisler durduruldu', 'setup.readyToLaunch': 'Başlatmaya hazır', 'setup.restartLocal': 'HomeInventory Local’ı Yeniden Başlat', 'setup.restart': 'HomeInventory’yi Yeniden Başlat', 'setup.launch': 'HomeInventory’yi Başlat', 'setup.checkingUpdates': 'Güncellemeler kontrol ediliyor…', 'setup.updateApp': 'Uygulamayı v{version} Sürümüne Güncelle', 'setup.storePreparation': 'HomeInventory Local, Microsoft Store paketindeki uygulama dosyalarını ve yerel çalışma ortamını hazırlayacak.', 'setup.chooseFolderHelp': 'Boş bir kurulum klasörü veya mevcut bir HomeInventory klasörü seçin.', 'setup.emptyFolderSelected': 'Boş kurulum klasörü seçildi. HomeInventory buraya indirilip kurulacak.', 'setup.invalidFolder': 'Bu klasör boş değil ve bir HomeInventory kurulum klasörü değil.',
  'update.kicker': 'Güncellemeler', 'update.syncPaused': 'Yönetilen uygulama eşitlemesi duraklatıldı', 'update.inProgress': 'Güncelleme sürüyor', 'update.checking': 'Güncellemeler kontrol ediliyor...', 'update.availableBeforeLaunch': 'Başlatmadan önce güncelleme var', 'update.checkedBeforeLaunch': 'Başlatmadan önce kontrol edildi', 'update.checkBeforeLaunch': 'Başlatmadan önce güncellemeleri kontrol et', 'update.previousAvailable': 'Önceki sürüm kullanılabilir durumda. Hazır olduğunuzda yeniden deneyin.', 'update.lookingForReleases': 'İmzalı launcher ve uygulama sürümleri aranıyor.', 'update.nodeUpgradeBeforeInstall': 'Bu güncelleme kurulmadan önce Node.js yükseltilmelidir.', 'update.installBeforeStart': 'HomeInventory’yi başlatmadan önce doğrulanmış güncellemeyi kurun.', 'update.noneAvailable': 'Şu anda güncelleme yok.', 'update.verifyBeforeStart': 'Servisleri başlatmadan önce sürümleri, imzaları ve gereksinimleri doğrulayın.', 'update.retrySync': 'Eşitlemeyi Yeniden Dene', 'update.updateFirst': 'Önce Güncelle', 'update.checkUpdates': 'Güncellemeleri Kontrol Et', 'update.checkForUpdates': 'Güncellemeleri kontrol et', 'update.upToDateNotice': 'Yazılımınız güncel.', 'update.checkFirst': 'Güncellemeyi başlatmadan önce güncellemeleri kontrol edin.', 'update.noInstallAvailable': 'Yazılımınız güncel. Kurulabilecek güncelleme yok.', 'update.initializing': 'Güncelleme hazırlanıyor...', 'update.backingUp': 'Veritabanı ve yüklemeler yedekleniyor...', 'update.downloading': 'Sürüm arşivi indiriliyor...', 'update.installing': 'npm ci bağımlılık kurulumu çalıştırılıyor...', 'update.complete': 'Güncelleme tamamlandı!', 'update.manage': 'Yazılım güncellemelerini yönetin ve kontrol edin.', 'update.checkingForUpdates': 'Güncellemeler kontrol ediliyor...', 'update.toVersion': '(v{version} sürümüne güncelle)', 'update.nodeRequired': 'Node.js Yükseltmesi Gerekli', 'update.nodeRequiredBody': 'En yeni uygulama sürümü Node.js v{version} veya üzerini gerektiriyor. Güncellemeye devam etmek için Node.js çalışma ortamını yükseltin.', 'update.appReleaseNotes': 'Uygulama Sürüm Notları', 'update.launcherReleaseNotes': 'Launcher Sürüm Notları', 'update.softwareCurrent': 'Yazılımınız güncel', 'update.latestVersions': 'HomeInventory ve masaüstü launcher’ın en yeni sürümlerini kullanıyorsunuz.', 'update.updateHomeInventory': 'HomeInventory’yi Güncelle', 'update.checkBeforeInstalling': 'Kurulumdan önce güncellemeleri kontrol edin', 'update.checkExplanation': 'Güncelleyiciyi çalıştırmadan önce launcher en yeni sürümü, imzaları, gerekli Node.js sürümünü ve uygulama ya da launcher güncellemelerini doğrulamalıdır.', 'update.temporarilyUnavailable': 'Güncelleme bilgileri geçici olarak kullanılamıyor',
  'update.stateStarting': 'Başlatılıyor', 'update.stateBackingUp': 'Yedekleniyor', 'update.stateDownloading': 'İndiriliyor', 'update.stateInstalling': 'Kuruluyor', 'update.stateCompleted': 'Tamamlandı', 'update.stateRollback': 'Geri alınıyor', 'update.stateRollbackComplete': 'Geri alma tamamlandı', 'update.stateFailed': 'Başarısız',
  'running.status': 'Çalışıyor', 'running.localAccess': 'Yerel erişim', 'running.ready': 'Envanteriniz hazır.', 'running.help': 'Bu cihazda açın veya aynı ağdaki başka bir cihazdan kodu tarayın.', 'running.standardLan': 'Standart LAN erişimi · sertifika kurulumu yok', 'running.lanPending': 'LAN durumu servisler ağa bağlandıktan sonra kontrol edilir.', 'running.openBrowser': 'Tarayıcıda aç', 'running.openApp': 'Uygulamayı aç', 'running.port': 'Port {port}', 'running.ports': 'Portlar {backend}/{frontend}', 'running.controls': 'Uygulama kontrolleri', 'running.settings': 'Launcher ayarları', 'running.stop': 'Yerel servisleri durdur', 'running.active': '{name} çalışıyor.',
  'https.setupLabel': 'Güvenli mobil kamera kurulumu', 'https.title': 'Güvenli mobil kamera erişimi', 'https.subtitle': 'İsteğe bağlı · çevrimdışı · alan adı veya harici servis yok', 'https.installTitle': '1 · Sertifikayı kurun', 'https.choosePlatform': 'iPhone / iPad veya Android seçin.', 'https.iosHelp': 'Profili kurun, ardından Ayarlar → Genel → Hakkında → Sertifika Güven Ayarları bölümünden tam güveni etkinleştirin.', 'https.downloadPrefix': 'QR şunu indirir:', 'https.downloadSuffix': 'bu launcher için oluşturulan herkese açık CA sertifikasıdır. Özel anahtar veya HomeInventory verisi içermez.', 'https.phoneBrand': 'Telefon markası', 'https.scanDownload': 'Sertifikayı indirmek için QR kodunu tarayın.', 'https.typicalPath': 'Tipik yol:', 'https.finishInstall': 'İndirilen dosyayı seçip kurulumu tamamlayın, ardından şunu tarayın:', 'https.openSecureApp': '2 · Güvenli uygulamayı açın', 'https.menuVariation': 'Menü adları Android sürümüne göre biraz değişebilir.', 'https.secureHelp': 'Kamera izninin çalışması için tarayıcı bu adresi sertifika uyarısı olmadan açmalıdır.', 'https.linksExpire': 'Kurulum bağlantıları 10 dakika sonra sona erer. CA özel anahtarı bu bilgisayardan ayrılmaz.', 'https.refreshLinks': 'Kurulum bağlantılarını yenile', 'https.disable': 'HTTPS’yi Devre Dışı Bırak', 'https.rotate': 'Güvenliği bozulan CA’yı yenile', 'https.removal': 'HTTPS’yi devre dışı bırakmak telefondaki güvenilir CA’yı kaldırmaz. Artık gerekmediğinde HomeInventory profilini/CA’sını cihaz ayarlarından kaldırın.', 'https.optionalLabel': 'İsteğe bağlı güvenli mobil kamera erişimi', 'https.wantCamera': 'Telefon kamerasıyla taramak ister misiniz?', 'https.oneTimeSetup': 'LAN kamera erişimi her telefonda tek seferlik güvenilir HTTPS kurulumu gerektirir.', 'https.enable': 'Güvenli mobil kamerayı etkinleştir', 'https.normalRemains': 'Normal HTTP erişimi kullanılmaya devam eder ve bu kurulum tamamen isteğe bağlıdır.', 'https.startFirst': 'Güvenli mobil kamera erişimini etkinleştirmeden önce HomeInventory’yi başlatın.', 'https.previewEnabled': 'Güvenli mobil kamera kurulumu tarayıcı önizlemesinde simüle edildi.', 'https.readyNotice': 'Güvenli mobil erişim {url} adresinde hazır. Açmadan önce yerel CA’yı her telefona kurun.', 'https.disabledNotice': 'Güvenli mobil erişim kapatıldı. Normal HTTP erişimi değişmedi.', 'https.rotateConfirm': 'HomeInventory yerel CA’sı yenilensin mi? Kayıtlı tüm telefonlar eski sertifikaya güvenmeyi bırakacak ve yenisini kurmak gerekecek.', 'https.rotatePreview': 'Yerel CA yenilemesi tarayıcı önizlemesinde simüle edildi.',
  'android.pixel': 'Google Pixel / standart Android', 'android.other': 'Diğer Android', 'android.samsungPath': 'Ayarlar → Güvenlik ve gizlilik → Diğer güvenlik ayarları → Cihaz depolama alanından yükle → CA sertifikası', 'android.pixelPath': 'Ayarlar → Güvenlik ve gizlilik → Diğer güvenlik ayarları → Şifreleme ve kimlik bilgileri → Sertifika yükle → CA sertifikası', 'android.otherPath': 'Ayarlar’ı açın, “Sertifika yükle” araması yapın ve CA sertifikasını seçin.',
  'advanced.title': 'Gelişmiş', 'advanced.configuration': 'Gelişmiş Yapılandırma', 'advanced.whatMatters': 'Burada önemli olanlar', 'advanced.emailLabel': 'E-posta:', 'advanced.emailHelp': 'Resend hem API anahtarı hem de doğrulanmış gönderici adresi gerektirir. Yalnızca anahtar yapılandırılmış görünebilir ama teslimat başarısız olur.', 'advanced.adminLabel': 'Yönetici:', 'advanced.adminHelp': 'Başlangıç Yönetici E-postası ilk güvenilir yöneticiyi öngörülebilir yapar.', 'advanced.networkLabel': 'Ağ:', 'advanced.networkStore': 'HomeInventory Local uygulama ve API için tek yerel port kullanır.', 'advanced.networkDesktop': 'Portlar yerelde boş olmalıdır; LAN erişimi ayrıca güvenlik duvarına ve aynı Wi-Fi ağına bağlıdır.', 'advanced.emailDelivery': 'E-posta Teslimi', 'advanced.resendHelp': 'Davet, doğrulama, yönetici postası ve parola sıfırlama e-postalarını etkinleştirir.', 'advanced.sender': 'Doğrulanmış Gönderici', 'advanced.senderHelp': 'Doğrulanmış bir Resend alan adından gönderici kullanın. Hızlı test için Resend onboarding@resend.dev adresine izin verir.', 'advanced.supportEmail': 'Destek E-postası', 'advanced.supportHelp': 'Yardım bağlantılarında ve giden e-posta altbilgilerinde gösterilir.', 'advanced.instanceAdmin': 'Örnek ve Yönetici', 'advanced.bootstrapAdmin': 'Başlangıç Yönetici E-postası', 'advanced.bootstrapHelp': 'Eşleşen hesap ilk kurulum veya giriş sırasında yönetici yetkisi alır.', 'advanced.envHelp': 'Launcher yalnızca doldurulan değerleri .env dosyasına yazar; mevcut yapılandırma korunur.', 'advanced.localPort': 'Yerel Port', 'advanced.networkPorts': 'Ağ Portları', 'advanced.apiPort': 'API Portu', 'advanced.uiPort': 'Arayüz Portu', 'advanced.storePortHelp': 'Geçerli aralık: 1024-65535. Varsayılan: 3001. Yalnızca başka bir uygulama aynı portu kullanıyorsa değiştirin.', 'advanced.desktopPortHelp': 'Geçerli aralık: 1024-65535. Varsayılanlar: API 3001, arayüz 5173. Yalnızca başka bir uygulama aynı portu kullanıyorsa değiştirin.', 'advanced.randomPort': 'Rastgele Boş Port Bul', 'advanced.randomPorts': 'Rastgele Boş Portlar Bul', 'advanced.usePort': '{port} Kullan', 'advanced.usePorts': '{backend}/{frontend} Kullan', 'advanced.otherDevices': 'Diğer cihazlardan erişim', 'advanced.sameWifiPrefix': 'Cihazları', 'advanced.sameWifi': 'aynı Wi-Fi ağında', 'advanced.firewall': 'İstenirse özel ağlar için Windows Güvenlik Duvarı’nda HomeInventory veya Node.js’e izin verin.', 'advanced.findIp': 'IP adresinizi bulun: Sistem Ayarları → Wi-Fi → Ayrıntılar → IP Adresi',
  'dev.console': 'Geliştirici Konsolu', 'dev.logs': 'Günlükler', 'dev.backups': 'Yedekler', 'dev.settings': 'Ayarlar', 'dev.updates': 'Güncellemeler', 'dev.backupDescription': 'Yerel verilerinizin ve medyanızın tek tıkla yedeği.', 'dev.backingUp': 'Yedekleniyor...', 'dev.backupNow': 'Şimdi Yedekle', 'dev.openBackup': 'Yedeği Aç', 'dev.installFolder': 'Kurulum Klasörü', 'dev.installFolderHelp': 'Yeni kurulum için boş bir klasör veya mevcut HomeInventory klasörü seçin.', 'dev.nodePath': 'Node Yolu', 'dev.npmPath': 'npm Yolu', 'dev.autoDetected': 'Otomatik algılandı', 'dev.nodePathHelp': 'Bunu yalnızca launcher Node kurulumunuzu bulamıyorsa ayarlayın.', 'dev.npmPathHelp': 'Bunu yalnızca masaüstü uygulaması npm’i algılayamıyorsa ayarlayın.', 'dev.openFolder': 'Klasörü Aç', 'dev.openData': 'Veriyi Aç', 'dev.resetDetection': 'Node/npm Algılamasını Sıfırla', 'dev.stopServer': 'Sunucuyu Durdur', 'dev.noLogs': 'Henüz günlük kaydı yok.', 'dev.choosePath': 'Yol seç', 'dev.openLocation': 'Konumu aç', 'dev.useDetectedPath': 'Otomatik algılanan yolu kullan',
};

const de: Dictionary = { ...en,
  'qr.code': 'QR-Code', 'qr.scan': 'Zum Verbinden scannen',
  'language.launcherLanguage': 'Launcher-Sprache', 'language.savedHelp': 'Wird sofort angewendet und auf diesem Gerät gespeichert.',
  'status.existingInstance': 'HomeInventory läuft bereits auf den ausgewählten Ports. Öffnen Sie die vorhandene Sitzung, statt eine zweite zu starten.', 'status.apiPortBusy': 'API-Port {port} ist belegt. Vorschlag: {suggested}.', 'status.uiPortBusy': 'UI-Port {port} ist belegt. Vorschlag: {suggested}.', 'status.bothPortsBusy': 'Ports {backend} und {frontend} sind belegt. Vorschlag: {suggestedBackend}/{suggestedFrontend}.', 'status.networkReady': 'Die Netzwerkadresse ist bereit. Falls ein anderes Gerät keine Verbindung herstellen kann, erlauben Sie HomeInventory oder Node.js in der Windows-Firewall für private Netzwerke.', 'status.lanUiBlocked': 'Die App-Oberfläche ist über die LAN-IP nicht erreichbar. Prüfen Sie Windows-Firewall und Host-Bindung.', 'status.lanApiBlocked': 'Die App-Oberfläche ist erreichbar, die API jedoch nicht über die LAN-IP.', 'status.lanBlocked': 'LAN-Prüfung fehlgeschlagen. Erlauben Sie HomeInventory oder Node.js in der Windows-Firewall für private Netzwerke und starten Sie die App neu.',
  'update.stateStarting': 'Wird gestartet', 'update.stateBackingUp': 'Sicherung läuft', 'update.stateDownloading': 'Wird heruntergeladen', 'update.stateInstalling': 'Wird installiert', 'update.stateCompleted': 'Abgeschlossen', 'update.stateRollback': 'Wird zurückgesetzt', 'update.stateRollbackComplete': 'Zurücksetzen abgeschlossen', 'update.stateFailed': 'Fehlgeschlagen',
  'language.en': 'English', 'language.tr': 'Türkçe', 'language.de': 'Deutsch', 'language.fr': 'Français', 'language.es': 'Español', 'common.launcher': 'Launcher', 'common.detected': 'Erkannt: {path}',
  'status.launcherReady': 'Launcher ist bereit.', 'status.browserPreview': 'Browser-Vorschau — Tauri-Befehle werden simuliert.', 'status.loadingEnvironment': 'Umgebung wird geladen…', 'status.noProfile': 'Kein Profil verfügbar.', 'status.apiPortRange': 'Der API-Port muss zwischen 1024 und 65535 liegen.', 'status.uiPortRange': 'Der UI-Port muss zwischen 1024 und 65535 liegen.', 'status.localPortRange': 'Der lokale Port muss zwischen 1024 und 65535 liegen.', 'status.portsDifferent': 'API- und UI-Port müssen unterschiedlich sein.', 'status.portsAvailable': 'Die Ports sind verfügbar.', 'status.localPortValid': 'Der lokale Port ist gültig.', 'status.previewPortsValid': 'Die Ports sind in der Browser-Vorschau gültig.', 'status.checkingPorts': 'Lokale Ports werden vor dem Start geprüft…', 'status.randomLocalPort': 'Verfügbarer lokaler Port {port} ausgewählt.', 'status.randomPorts': 'Verfügbare API-/UI-Ports {backend}/{frontend} ausgewählt.', 'status.defaultPortsBusy': 'Die Standardports sind belegt. Start auf {backend}/{frontend}.', 'status.startPreview': '{name} wird gestartet: im Browsermodus simuliert.', 'status.stopPreview': 'Aktives Profil beendet: im Browsermodus simuliert.', 'status.setupStopped': 'HomeInventory wurde beendet, bevor der Start abgeschlossen war. Öffnen Sie die Entwicklerwerkzeuge für Protokolle.', 'status.folderPickerDesktop': 'Die Ordnerauswahl ist im Desktop-Launcher verfügbar.', 'status.folderSelected': 'Installationsordner ausgewählt.', 'status.folderCleared': 'Installationsordner geleert.', 'status.pathPickerDesktop': 'Die Pfadauswahl ist im Desktop-Launcher verfügbar.', 'status.pathUpdated': 'Pfad aktualisiert. Die Werkzeugerkennung wird automatisch aktualisiert.', 'status.pathEmpty': 'Der Pfad für {label} ist leer.', 'status.folderRevealDesktop': 'Das Anzeigen von Ordnern ist im Desktop-Launcher verfügbar.', 'status.pathOpened': '{label} wurde geöffnet.', 'status.nodeOverridesCleared': 'Node-/npm-Überschreibungen entfernt. Die automatische Erkennung ist aktiv.', 'status.backupPreview': 'Sicherung für {name} erstellt: im Browsermodus simuliert.',
  'setup.elapsedBundled': 'Vergangene Zeit: {elapsed}. Gebündelte App-Dateien und Laufzeit werden vorbereitet.', 'setup.elapsedInstall': 'Vergangene Zeit: {elapsed}. Die Erstinstallation kann je nach npm- und Netzwerkgeschwindigkeit einige Minuten dauern.', 'setup.runtimeHelp': 'Starten Sie HomeInventory Local, um die im Microsoft-Store-Paket enthaltene Laufzeit vorzubereiten.', 'setup.nodeHelpPrefix': 'Laden Sie Node.js von', 'setup.nodeHelpSuffix': 'herunter und installieren Sie es, um fortzufahren.', 'setup.launchOn': 'Auf {backend}/{frontend} starten', 'setup.restartLocal': 'HomeInventory Local neu starten', 'setup.storePreparation': 'HomeInventory Local bereitet die gebündelten App-Dateien und die lokale Laufzeit aus dem Microsoft-Store-Paket vor.', 'setup.chooseFolderHelp': 'Wählen Sie einen leeren Installationsordner oder einen vorhandenen HomeInventory-Ordner.', 'setup.emptyFolderSelected': 'Leerer Installationsordner ausgewählt. HomeInventory wird hier heruntergeladen und installiert.', 'setup.invalidFolder': 'Dieser Ordner ist nicht leer und kein HomeInventory-Installationsordner.',
  'update.previousAvailable': 'Die vorherige Version bleibt verfügbar. Versuchen Sie es erneut, wenn Sie bereit sind.', 'update.lookingForReleases': 'Signierte Launcher- und App-Versionen werden gesucht.', 'update.nodeUpgradeBeforeInstall': 'Node.js muss aktualisiert werden, bevor dieses Update installiert werden kann.', 'update.installBeforeStart': 'Installieren Sie das verifizierte Update, bevor Sie HomeInventory starten.', 'update.noneAvailable': 'Derzeit ist kein Update verfügbar.', 'update.verifyBeforeStart': 'Prüfen Sie Versionen, Signaturen und Anforderungen, bevor Sie die Dienste starten.', 'update.checkFirst': 'Suchen Sie nach Updates, bevor Sie das Update starten.', 'update.noInstallAvailable': 'Ihre Software ist aktuell. Es ist kein installierbares Update verfügbar.', 'update.initializing': 'Update wird vorbereitet...', 'update.backingUp': 'Datenbank und Uploads werden gesichert...', 'update.downloading': 'Versionsarchiv wird heruntergeladen...', 'update.installing': 'npm-ci-Abhängigkeiten werden installiert...', 'update.complete': 'Update abgeschlossen!', 'update.toVersion': '(Auf v{version} aktualisieren)', 'update.nodeRequiredBody': 'Die neueste App-Version benötigt Node.js v{version} oder höher. Aktualisieren Sie Ihre Node.js-Laufzeit, um fortzufahren.', 'update.checkExplanation': 'Vor dem Update sollte der Launcher die neueste Version, Signaturen, die erforderliche Node.js-Version sowie verfügbare App- oder Launcher-Updates prüfen.',
  'https.ios': 'iPhone / iPad', 'https.android': 'Android', 'https.optionalLabel': 'Optionaler sicherer mobiler Kamerazugriff', 'https.startFirst': 'Starten Sie HomeInventory, bevor Sie den sicheren mobilen Kamerazugriff aktivieren.', 'https.previewEnabled': 'Die sichere mobile Kameraeinrichtung wird in der Browser-Vorschau simuliert.', 'https.readyNotice': 'Der sichere mobile Zugriff ist unter {url} bereit. Installieren Sie die lokale CA auf jedem Telefon, bevor Sie die Adresse öffnen.', 'https.disabledNotice': 'Der sichere mobile Zugriff ist deaktiviert. Der normale HTTP-Zugriff bleibt unverändert.', 'https.rotateConfirm': 'Lokale HomeInventory-CA erneuern? Alle registrierten Telefone vertrauen dem alten Zertifikat anschließend nicht mehr und müssen das neue installieren.', 'https.rotatePreview': 'Die Erneuerung der lokalen CA wird in der Browser-Vorschau simuliert.',
  'android.samsung': 'Samsung Galaxy',
  'advanced.emailHelp': 'Resend benötigt sowohl einen API-Schlüssel als auch eine verifizierte Absenderadresse. Ein Schlüssel allein kann konfiguriert wirken, obwohl der Versand fehlschlägt.', 'advanced.adminHelp': 'Die Administrator-E-Mail bei der Einrichtung legt den ersten vertrauenswürdigen Administrator eindeutig fest.', 'advanced.networkStore': 'HomeInventory Local verwendet einen lokalen Port für App und API.', 'advanced.networkDesktop': 'Die Ports müssen lokal frei sein; der LAN-Zugriff hängt außerdem von Firewall und gemeinsamem WLAN ab.', 'advanced.resendKey': 'Resend-API-Schlüssel', 'advanced.resendHelp': 'Aktiviert Einladungen, Verifizierung, Administrator-E-Mails und E-Mails zum Zurücksetzen des Passworts.', 'advanced.senderHelp': 'Verwenden Sie einen Absender aus einer verifizierten Resend-Domain. Für schnelle Tests erlaubt Resend onboarding@resend.dev.', 'advanced.supportHelp': 'Wird in Hilfelinks und Fußzeilen ausgehender E-Mails angezeigt.', 'advanced.bootstrapHelp': 'Das passende Konto erhält bei der ersten Einrichtung oder Anmeldung Administratorrechte.', 'advanced.envHelp': 'Der Launcher schreibt nur ausgefüllte Werte in .env; die bestehende Konfiguration bleibt erhalten.', 'advanced.storePortHelp': 'Gültiger Bereich: 1024–65535. Standard: 3001. Nur ändern, wenn eine andere App denselben Port verwendet.', 'advanced.desktopPortHelp': 'Gültiger Bereich: 1024–65535. Standards: API 3001, UI 5173. Nur ändern, wenn eine andere App denselben Port verwendet.', 'advanced.usePort': '{port} verwenden', 'advanced.usePorts': '{backend}/{frontend} verwenden',
  'language.label': 'Sprache', 'common.close': 'Schließen', 'common.clear': 'Leeren', 'common.required': 'Erforderlich', 'common.recommended': 'Empfohlen', 'common.ready': 'Bereit', 'common.offline': 'Offline', 'common.checkAgain': 'Erneut prüfen', 'common.checking': 'Wird geprüft…', 'common.managedApp': 'Verwaltete App',
  'setup.subtitle': 'Ihr privates Haushaltsinventar', 'setup.localFirst': 'Lokal zuerst', 'setup.waiting': 'Initialisierung wird vorbereitet…', 'setup.nodeRequired': 'Node.js ist erforderlich.', 'setup.preparingFiles': 'Anwendungsdateien werden vorbereitet…', 'setup.installing': 'Abhängigkeiten werden installiert und die App wird vorbereitet…', 'setup.failed': 'Die Einrichtung wurde nach einem Fehler beendet. Wählen Sie einen anderen Installationsordner und versuchen Sie es erneut.', 'setup.runtimeNotReady': 'Gebündelte Laufzeit ist nicht bereit', 'setup.nodeNotFound': 'Node.js wurde nicht gefunden', 'setup.checkingLocalPorts': 'Lokale Ports werden geprüft…', 'setup.launchLocal': 'HomeInventory Local starten', 'setup.chooseInstallFolder': 'Installationsordner wählen', 'setup.installLaunch': 'Installieren und starten', 'setup.openRunning': 'Laufendes HomeInventory öffnen', 'setup.initializeLaunch': 'Initialisieren und starten', 'setup.developerTools': 'Entwicklerwerkzeuge', 'setup.hideConsole': 'Konsole ausblenden', 'setup.systemConsole': 'Systemkonsole', 'setup.connectingRegistry': 'Verbindung mit Ihrem Inventar wird hergestellt', 'setup.startingServices': 'Dienste werden gestartet…', 'setup.launching': 'Wird gestartet…', 'setup.connectingDatabase': 'Verbindung zur Datenbank wird hergestellt…', 'setup.servicesStopped': 'Dienste wurden beendet', 'setup.readyToLaunch': 'Startbereit', 'setup.restart': 'HomeInventory neu starten', 'setup.launch': 'HomeInventory starten', 'setup.checkingUpdates': 'Updates werden gesucht…', 'setup.updateApp': 'App auf v{version} aktualisieren',
  'update.kicker': 'Updates', 'update.syncPaused': 'Synchronisierung der verwalteten App pausiert', 'update.inProgress': 'Update läuft', 'update.checking': 'Updates werden gesucht...', 'update.availableBeforeLaunch': 'Update vor dem Start verfügbar', 'update.checkedBeforeLaunch': 'Vor dem Start geprüft', 'update.checkBeforeLaunch': 'Vor dem Start nach Updates suchen', 'update.retrySync': 'Synchronisierung wiederholen', 'update.updateFirst': 'Zuerst aktualisieren', 'update.checkUpdates': 'Updates suchen', 'update.checkForUpdates': 'Nach Updates suchen', 'update.upToDateNotice': 'Ihre Software ist aktuell.', 'update.manage': 'Softwareupdates verwalten und suchen.', 'update.checkingForUpdates': 'Updates werden gesucht...', 'update.nodeRequired': 'Node.js-Upgrade erforderlich', 'update.appReleaseNotes': 'Versionshinweise der App', 'update.launcherReleaseNotes': 'Versionshinweise des Launchers', 'update.softwareCurrent': 'Ihre Software ist aktuell', 'update.latestVersions': 'Sie verwenden die neueste Version von HomeInventory und des Desktop-Launchers.', 'update.updateHomeInventory': 'HomeInventory aktualisieren', 'update.checkBeforeInstalling': 'Vor der Installation nach Updates suchen', 'update.temporarilyUnavailable': 'Updateinformationen sind vorübergehend nicht verfügbar',
  'running.status': 'Läuft', 'running.localAccess': 'Lokaler Zugriff', 'running.ready': 'Ihr Inventar ist bereit.', 'running.help': 'Öffnen Sie es auf diesem Gerät oder scannen Sie den Code mit einem anderen Gerät im selben Netzwerk.', 'running.standardLan': 'Standard-LAN-Zugriff · keine Zertifikatseinrichtung', 'running.lanPending': 'Der LAN-Status wird geprüft, nachdem die Dienste mit dem Netzwerk verbunden sind.', 'running.openBrowser': 'Im Browser öffnen', 'running.openApp': 'App öffnen', 'running.port': 'Port {port}', 'running.ports': 'Ports {backend}/{frontend}', 'running.controls': 'App-Steuerung', 'running.settings': 'Launcher-Einstellungen', 'running.stop': 'Lokale Dienste beenden', 'running.active': '{name} läuft.',
  'https.setupLabel': 'Sichere mobile Kamera einrichten', 'https.title': 'Sicherer mobiler Kamerazugriff', 'https.subtitle': 'Optional · offline · keine Domain oder externer Dienst', 'https.installTitle': '1 · Zertifikat installieren', 'https.choosePlatform': 'iPhone / iPad oder Android wählen.', 'https.iosHelp': 'Installieren Sie das Profil und aktivieren Sie anschließend das volle Vertrauen unter Einstellungen → Allgemein → Info → Zertifikatsvertrauenseinstellungen.', 'https.downloadPrefix': 'Der QR-Code lädt', 'https.downloadSuffix': 'das für diesen Launcher erzeugte öffentliche CA-Zertifikat herunter. Es enthält keinen privaten Schlüssel und keine HomeInventory-Daten.', 'https.phoneBrand': 'Telefonmarke', 'https.scanDownload': 'Scannen Sie den QR-Code, um das Zertifikat herunterzuladen.', 'https.typicalPath': 'Typischer Pfad:', 'https.finishInstall': 'Wählen Sie die heruntergeladene Datei, schließen Sie die Installation ab und scannen Sie dann', 'https.openSecureApp': '2 · Sichere App öffnen', 'https.menuVariation': 'Menünamen können je nach Android-Version leicht abweichen.', 'https.secureHelp': 'Der Browser muss diese Adresse ohne Zertifikatswarnung öffnen, damit die Kameraberechtigung funktioniert.', 'https.linksExpire': 'Einrichtungslinks laufen nach 10 Minuten ab. Der private CA-Schlüssel verlässt diesen Computer nie.', 'https.refreshLinks': 'Einrichtungslinks aktualisieren', 'https.disable': 'HTTPS deaktivieren', 'https.rotate': 'Kompromittierte CA erneuern', 'https.removal': 'Durch das Deaktivieren von HTTPS wird die vertrauenswürdige CA nicht vom Telefon entfernt. Entfernen Sie das HomeInventory-Profil bzw. die CA in den Geräteeinstellungen, wenn sie nicht mehr benötigt wird.', 'https.wantCamera': 'Mit der Telefonkamera scannen?', 'https.oneTimeSetup': 'Der LAN-Kamerazugriff erfordert auf jedem Telefon eine einmalige vertrauenswürdige HTTPS-Einrichtung.', 'https.enable': 'Sichere mobile Kamera aktivieren', 'https.normalRemains': 'Der normale HTTP-Zugriff bleibt verfügbar; diese Einrichtung ist vollständig optional.',
  'android.pixel': 'Google Pixel / Standard-Android', 'android.other': 'Anderes Android-Gerät', 'android.samsungPath': 'Einstellungen → Sicherheit und Datenschutz → Weitere Sicherheitseinstellungen → Aus Gerätespeicher installieren → CA-Zertifikat', 'android.pixelPath': 'Einstellungen → Sicherheit und Datenschutz → Weitere Sicherheitseinstellungen → Verschlüsselung und Anmeldedaten → Zertifikat installieren → CA-Zertifikat', 'android.otherPath': 'Öffnen Sie die Einstellungen, suchen Sie nach „Zertifikat installieren“ und wählen Sie CA-Zertifikat.',
  'advanced.title': 'Erweitert', 'advanced.configuration': 'Erweiterte Konfiguration', 'advanced.whatMatters': 'Darauf kommt es an', 'advanced.emailLabel': 'E-Mail:', 'advanced.adminLabel': 'Administrator:', 'advanced.networkLabel': 'Netzwerk:', 'advanced.emailDelivery': 'E-Mail-Versand', 'advanced.sender': 'Verifizierter Absender', 'advanced.supportEmail': 'Support-E-Mail', 'advanced.instanceAdmin': 'Instanz und Administrator', 'advanced.bootstrapAdmin': 'Administrator-E-Mail bei Einrichtung', 'advanced.localPort': 'Lokaler Port', 'advanced.networkPorts': 'Netzwerkports', 'advanced.apiPort': 'API-Port', 'advanced.uiPort': 'UI-Port', 'advanced.randomPort': 'Freien Zufallsport finden', 'advanced.randomPorts': 'Freie Zufallsports finden', 'advanced.otherDevices': 'Zugriff von anderen Geräten', 'advanced.sameWifiPrefix': 'Geräte im', 'advanced.sameWifi': 'selben WLAN', 'advanced.firewall': 'Erlauben Sie HomeInventory oder Node.js bei Aufforderung in der Windows-Firewall für private Netzwerke.', 'advanced.findIp': 'IP-Adresse finden: Systemeinstellungen → WLAN → Details → IP-Adresse',
  'dev.console': 'Entwicklerkonsole', 'dev.logs': 'Protokolle', 'dev.backups': 'Sicherungen', 'dev.settings': 'Einstellungen', 'dev.updates': 'Updates', 'dev.backupDescription': 'Sicherung Ihrer lokalen Daten und Medien mit einem Klick.', 'dev.backingUp': 'Sicherung läuft...', 'dev.backupNow': 'Jetzt sichern', 'dev.openBackup': 'Sicherung öffnen', 'dev.installFolder': 'Installationsordner', 'dev.installFolderHelp': 'Wählen Sie für eine neue Installation einen leeren Ordner oder einen vorhandenen HomeInventory-Ordner.', 'dev.nodePath': 'Node-Pfad', 'dev.npmPath': 'npm-Pfad', 'dev.autoDetected': 'Automatisch erkannt', 'dev.nodePathHelp': 'Nur festlegen, wenn der Launcher Ihre Node-Installation nicht findet.', 'dev.npmPathHelp': 'Nur festlegen, wenn die Desktop-App npm nicht erkennt.', 'dev.openFolder': 'Ordner öffnen', 'dev.openData': 'Daten öffnen', 'dev.resetDetection': 'Node/npm-Erkennung zurücksetzen', 'dev.stopServer': 'Server beenden', 'dev.noLogs': 'Noch keine Protokolleinträge.', 'dev.choosePath': 'Pfad wählen', 'dev.openLocation': 'Speicherort öffnen', 'dev.useDetectedPath': 'Automatisch erkannten Pfad verwenden',
};

const fr: Dictionary = { ...en,
  'qr.code': 'QR code', 'qr.scan': 'Scanner pour se connecter',
  'language.launcherLanguage': 'Langue du launcher', 'language.savedHelp': 'Appliquée immédiatement et mémorisée sur cet appareil.',
  'status.existingInstance': 'HomeInventory fonctionne déjà sur les ports sélectionnés. Ouvrez la session existante au lieu d’en démarrer une autre.', 'status.apiPortBusy': 'Le port API {port} est occupé. Suggestion : {suggested}.', 'status.uiPortBusy': 'Le port de l’interface {port} est occupé. Suggestion : {suggested}.', 'status.bothPortsBusy': 'Les ports {backend} et {frontend} sont occupés. Suggestion : {suggestedBackend}/{suggestedFrontend}.', 'status.networkReady': 'L’adresse réseau est prête. Si un autre appareil ne peut pas se connecter, autorisez HomeInventory ou Node.js dans le pare-feu Windows pour les réseaux privés.', 'status.lanUiBlocked': 'L’interface n’est pas accessible via l’adresse IP du LAN. Vérifiez le pare-feu Windows et l’écoute réseau.', 'status.lanApiBlocked': 'L’interface est accessible, mais l’API ne l’est pas via l’adresse IP du LAN.', 'status.lanBlocked': 'La vérification du LAN a échoué. Autorisez HomeInventory ou Node.js dans le pare-feu Windows pour les réseaux privés, puis redémarrez l’application.',
  'update.stateStarting': 'Démarrage', 'update.stateBackingUp': 'Sauvegarde', 'update.stateDownloading': 'Téléchargement', 'update.stateInstalling': 'Installation', 'update.stateCompleted': 'Terminé', 'update.stateRollback': 'Restauration', 'update.stateRollbackComplete': 'Restauration terminée', 'update.stateFailed': 'Échec',
  'language.en': 'English', 'language.tr': 'Türkçe', 'language.de': 'Deutsch', 'language.fr': 'Français', 'language.es': 'Español', 'common.launcher': 'Launcher', 'common.detected': 'Détecté : {path}',
  'status.launcherReady': 'Le launcher est prêt.', 'status.browserPreview': 'Aperçu navigateur — les commandes Tauri sont simulées.', 'status.loadingEnvironment': 'Chargement de l’environnement…', 'status.noProfile': 'Aucun profil disponible.', 'status.apiPortRange': 'Le port API doit être compris entre 1024 et 65535.', 'status.uiPortRange': 'Le port de l’interface doit être compris entre 1024 et 65535.', 'status.localPortRange': 'Le port local doit être compris entre 1024 et 65535.', 'status.portsDifferent': 'Les ports API et interface doivent être différents.', 'status.portsAvailable': 'Les ports sont disponibles.', 'status.localPortValid': 'Le port local est valide.', 'status.previewPortsValid': 'Les ports semblent valides dans l’aperçu navigateur.', 'status.checkingPorts': 'Vérification des ports locaux avant le lancement…', 'status.randomLocalPort': 'Port local disponible {port} sélectionné.', 'status.randomPorts': 'Ports API/interface disponibles {backend}/{frontend} sélectionnés.', 'status.defaultPortsBusy': 'Les ports par défaut sont occupés. Lancement sur {backend}/{frontend}.', 'status.startPreview': 'Démarrage de {name} : simulé en mode navigateur.', 'status.stopPreview': 'Profil actif arrêté : simulé en mode navigateur.', 'status.setupStopped': 'HomeInventory s’est arrêté avant la fin du démarrage. Ouvrez les outils de développement pour consulter les journaux.', 'status.folderPickerDesktop': 'Le sélecteur de dossier est disponible dans le launcher de bureau.', 'status.folderSelected': 'Dossier d’installation sélectionné.', 'status.folderCleared': 'Dossier d’installation effacé.', 'status.pathPickerDesktop': 'Le sélecteur de chemin est disponible dans le launcher de bureau.', 'status.pathUpdated': 'Chemin mis à jour. La détection des outils sera actualisée automatiquement.', 'status.pathEmpty': 'Le chemin {label} est vide.', 'status.folderRevealDesktop': 'L’affichage du dossier est disponible dans le launcher de bureau.', 'status.pathOpened': '{label} a été ouvert.', 'status.nodeOverridesCleared': 'Les chemins Node/npm personnalisés ont été effacés. La détection automatique est active.', 'status.backupPreview': 'Sauvegarde créée pour {name} : simulée en mode navigateur.',
  'setup.elapsedBundled': 'Temps écoulé : {elapsed}. Préparation des fichiers intégrés et de l’environnement.', 'setup.elapsedInstall': 'Temps écoulé : {elapsed}. La première installation peut prendre quelques minutes selon npm et la vitesse du réseau.', 'setup.runtimeHelp': 'Lancez HomeInventory Local pour préparer l’environnement inclus dans le paquet Microsoft Store.', 'setup.nodeHelpPrefix': 'Téléchargez et installez Node.js depuis', 'setup.nodeHelpSuffix': 'pour continuer.', 'setup.launchOn': 'Lancer sur {backend}/{frontend}', 'setup.restartLocal': 'Redémarrer HomeInventory Local', 'setup.storePreparation': 'HomeInventory Local va préparer les fichiers intégrés et l’environnement local du paquet Microsoft Store.', 'setup.chooseFolderHelp': 'Choisissez un dossier d’installation vide ou un dossier HomeInventory existant.', 'setup.emptyFolderSelected': 'Dossier d’installation vide sélectionné. HomeInventory y sera téléchargé et installé.', 'setup.invalidFolder': 'Ce dossier n’est pas vide et ne correspond pas à une installation HomeInventory.',
  'update.previousAvailable': 'La version précédente reste disponible. Réessayez lorsque vous êtes prêt.', 'update.lookingForReleases': 'Recherche des versions signées du launcher et de l’application.', 'update.nodeUpgradeBeforeInstall': 'Node.js doit être mis à niveau avant l’installation de cette mise à jour.', 'update.installBeforeStart': 'Installez la mise à jour vérifiée avant de lancer HomeInventory.', 'update.noneAvailable': 'Aucune mise à jour n’est disponible actuellement.', 'update.verifyBeforeStart': 'Vérifiez les versions, signatures et prérequis avant de démarrer les services.', 'update.checkFirst': 'Recherchez des mises à jour avant de lancer la mise à jour.', 'update.noInstallAvailable': 'Votre logiciel est à jour. Aucune mise à jour ne peut être installée.', 'update.initializing': 'Préparation de la mise à jour...', 'update.backingUp': 'Sauvegarde de la base de données et des fichiers...', 'update.downloading': 'Téléchargement de l’archive de version...', 'update.installing': 'Installation des dépendances avec npm ci...', 'update.complete': 'Mise à jour terminée !', 'update.toVersion': '(Mettre à jour vers v{version})', 'update.nodeRequiredBody': 'La dernière version de l’application nécessite Node.js v{version} ou une version ultérieure. Mettez à niveau votre environnement Node.js pour continuer.', 'update.checkExplanation': 'Avant la mise à jour, le launcher doit vérifier la dernière version, les signatures, la version Node.js requise et les mises à jour disponibles pour l’application ou le launcher.',
  'https.ios': 'iPhone / iPad', 'https.android': 'Android', 'https.optionalLabel': 'Accès sécurisé facultatif à la caméra mobile', 'https.startFirst': 'Démarrez HomeInventory avant d’activer l’accès sécurisé à la caméra mobile.', 'https.previewEnabled': 'La configuration sécurisée de la caméra mobile est simulée dans l’aperçu navigateur.', 'https.readyNotice': 'L’accès mobile sécurisé est prêt à l’adresse {url}. Installez l’autorité locale sur chaque téléphone avant de l’ouvrir.', 'https.disabledNotice': 'L’accès mobile sécurisé est désactivé. L’accès HTTP normal reste inchangé.', 'https.rotateConfirm': 'Renouveler l’autorité locale HomeInventory ? Tous les téléphones inscrits cesseront de faire confiance à l’ancien certificat et devront installer le nouveau.', 'https.rotatePreview': 'Le renouvellement de l’autorité locale est simulé dans l’aperçu navigateur.',
  'android.samsung': 'Samsung Galaxy',
  'advanced.emailHelp': 'Resend nécessite une clé API et une adresse d’expéditeur vérifiée. Une clé seule peut sembler configurée alors que l’envoi échoue.', 'advanced.adminHelp': 'L’e-mail administrateur initial permet de définir clairement le premier administrateur de confiance.', 'advanced.networkStore': 'HomeInventory Local utilise un seul port local pour l’application et l’API.', 'advanced.networkDesktop': 'Les ports doivent être libres localement ; l’accès LAN dépend aussi du pare-feu et du même réseau Wi-Fi.', 'advanced.resendKey': 'Clé API Resend', 'advanced.resendHelp': 'Active les invitations, la vérification, les e-mails administrateur et la réinitialisation du mot de passe.', 'advanced.senderHelp': 'Utilisez un expéditeur provenant d’un domaine Resend vérifié. Pour un test rapide, Resend autorise onboarding@resend.dev.', 'advanced.supportHelp': 'Affiché dans les liens d’aide et les pieds de page des e-mails sortants.', 'advanced.bootstrapHelp': 'Le compte associé reçoit les droits administrateur lors de la première configuration ou connexion.', 'advanced.envHelp': 'Le launcher n’écrit que les valeurs renseignées dans .env ; la configuration existante est conservée.', 'advanced.storePortHelp': 'Plage valide : 1024–65535. Valeur par défaut : 3001. À modifier uniquement si une autre application utilise ce port.', 'advanced.desktopPortHelp': 'Plage valide : 1024–65535. Valeurs par défaut : API 3001, interface 5173. À modifier uniquement si une autre application utilise le même port.', 'advanced.usePort': 'Utiliser {port}', 'advanced.usePorts': 'Utiliser {backend}/{frontend}',
  'language.label': 'Langue', 'common.close': 'Fermer', 'common.clear': 'Effacer', 'common.required': 'Requis', 'common.recommended': 'Recommandé', 'common.ready': 'Prêt', 'common.offline': 'Hors ligne', 'common.checkAgain': 'Vérifier à nouveau', 'common.checking': 'Vérification…', 'common.managedApp': 'Application gérée',
  'setup.subtitle': 'Votre inventaire domestique privé', 'setup.localFirst': 'Local avant tout', 'setup.waiting': 'En attente d’initialisation…', 'setup.nodeRequired': 'Node.js est requis.', 'setup.preparingFiles': 'Préparation des fichiers de l’application…', 'setup.installing': 'Installation des dépendances et préparation de l’application…', 'setup.failed': 'La configuration s’est arrêtée après une erreur. Choisissez un autre dossier d’installation et réessayez.', 'setup.runtimeNotReady': 'Environnement intégré non prêt', 'setup.nodeNotFound': 'Node.js introuvable', 'setup.checkingLocalPorts': 'Vérification des ports locaux…', 'setup.launchLocal': 'Lancer HomeInventory Local', 'setup.chooseInstallFolder': 'Choisir le dossier d’installation', 'setup.installLaunch': 'Installer et lancer', 'setup.openRunning': 'Ouvrir HomeInventory en cours', 'setup.initializeLaunch': 'Initialiser et lancer', 'setup.developerTools': 'Outils de développement', 'setup.hideConsole': 'Masquer la console', 'setup.systemConsole': 'Console système', 'setup.connectingRegistry': 'Connexion à votre inventaire', 'setup.startingServices': 'Démarrage des services…', 'setup.launching': 'Lancement…', 'setup.connectingDatabase': 'Connexion à la base de données…', 'setup.servicesStopped': 'Les services sont arrêtés', 'setup.readyToLaunch': 'Prêt à démarrer', 'setup.restart': 'Redémarrer HomeInventory', 'setup.launch': 'Lancer HomeInventory', 'setup.checkingUpdates': 'Recherche de mises à jour…', 'setup.updateApp': 'Mettre l’application à jour vers v{version}',
  'update.kicker': 'Mises à jour', 'update.syncPaused': 'Synchronisation de l’application gérée en pause', 'update.inProgress': 'Mise à jour en cours', 'update.checking': 'Recherche de mises à jour...', 'update.availableBeforeLaunch': 'Mise à jour disponible avant le lancement', 'update.checkedBeforeLaunch': 'Vérifié avant le lancement', 'update.checkBeforeLaunch': 'Vérifier avant le lancement', 'update.retrySync': 'Réessayer la synchronisation', 'update.updateFirst': 'Mettre à jour d’abord', 'update.checkUpdates': 'Vérifier les mises à jour', 'update.checkForUpdates': 'Rechercher des mises à jour', 'update.upToDateNotice': 'Votre logiciel est à jour.', 'update.manage': 'Gérez et recherchez les mises à jour logicielles.', 'update.checkingForUpdates': 'Recherche de mises à jour...', 'update.nodeRequired': 'Mise à niveau de Node.js requise', 'update.appReleaseNotes': 'Notes de version de l’application', 'update.launcherReleaseNotes': 'Notes de version du launcher', 'update.softwareCurrent': 'Votre logiciel est à jour', 'update.latestVersions': 'Vous utilisez la dernière version de HomeInventory et du launcher de bureau.', 'update.updateHomeInventory': 'Mettre HomeInventory à jour', 'update.checkBeforeInstalling': 'Vérifier avant l’installation', 'update.temporarilyUnavailable': 'Les informations de mise à jour sont temporairement indisponibles',
  'running.status': 'En cours', 'running.localAccess': 'Accès local', 'running.ready': 'Votre inventaire est prêt.', 'running.help': 'Ouvrez-le sur cet appareil ou scannez le code depuis un autre appareil du même réseau.', 'running.standardLan': 'Accès LAN standard · aucune configuration de certificat', 'running.lanPending': 'L’état du LAN est vérifié après la connexion des services au réseau.', 'running.openBrowser': 'Ouvrir dans le navigateur', 'running.openApp': 'Ouvrir l’application', 'running.port': 'Port {port}', 'running.ports': 'Ports {backend}/{frontend}', 'running.controls': 'Commandes de l’application', 'running.settings': 'Paramètres du launcher', 'running.stop': 'Arrêter les services locaux', 'running.active': '{name} est en cours.',
  'https.setupLabel': 'Configuration sécurisée de la caméra mobile', 'https.title': 'Accès sécurisé à la caméra mobile', 'https.subtitle': 'Facultatif · hors ligne · sans domaine ni service externe', 'https.installTitle': '1 · Installer le certificat', 'https.choosePlatform': 'Choisissez iPhone / iPad ou Android.', 'https.iosHelp': 'Installez le profil, puis activez la confiance totale dans Réglages → Général → Informations → Réglages des certificats.', 'https.downloadPrefix': 'Le QR code télécharge', 'https.downloadSuffix': 'le certificat d’autorité public généré pour ce launcher. Il ne contient aucune clé privée ni donnée HomeInventory.', 'https.phoneBrand': 'Marque du téléphone', 'https.scanDownload': 'Scannez le QR code pour télécharger le certificat.', 'https.typicalPath': 'Chemin habituel :', 'https.finishInstall': 'Sélectionnez le fichier téléchargé, terminez l’installation, puis scannez', 'https.openSecureApp': '2 · Ouvrir l’application sécurisée', 'https.menuVariation': 'Les noms de menus peuvent varier légèrement selon la version d’Android.', 'https.secureHelp': 'Le navigateur doit ouvrir cette adresse sans avertissement de certificat pour que l’autorisation de la caméra fonctionne.', 'https.linksExpire': 'Les liens d’installation expirent après 10 minutes. La clé privée de l’autorité ne quitte jamais cet ordinateur.', 'https.refreshLinks': 'Actualiser les liens d’installation', 'https.disable': 'Désactiver HTTPS', 'https.rotate': 'Renouveler l’autorité compromise', 'https.removal': 'La désactivation de HTTPS ne supprime pas l’autorité approuvée du téléphone. Supprimez le profil ou l’autorité HomeInventory dans les réglages lorsqu’ils ne sont plus nécessaires.', 'https.wantCamera': 'Scanner avec la caméra du téléphone ?', 'https.oneTimeSetup': 'L’accès à la caméra sur le LAN nécessite une configuration HTTPS approuvée, une fois par téléphone.', 'https.enable': 'Activer la caméra mobile sécurisée', 'https.normalRemains': 'L’accès HTTP normal reste disponible et cette configuration est entièrement facultative.',
  'android.pixel': 'Google Pixel / Android standard', 'android.other': 'Autre appareil Android', 'android.samsungPath': 'Paramètres → Sécurité et confidentialité → Autres paramètres de sécurité → Installer depuis le stockage de l’appareil → Certificat d’autorité', 'android.pixelPath': 'Paramètres → Sécurité et confidentialité → Autres paramètres de sécurité → Chiffrement et identifiants → Installer un certificat → Certificat d’autorité', 'android.otherPath': 'Ouvrez les paramètres, recherchez « Installer un certificat », puis choisissez Certificat d’autorité.',
  'advanced.title': 'Avancé', 'advanced.configuration': 'Configuration avancée', 'advanced.whatMatters': 'Points importants', 'advanced.emailLabel': 'E-mail :', 'advanced.adminLabel': 'Administrateur :', 'advanced.networkLabel': 'Réseau :', 'advanced.emailDelivery': 'Envoi des e-mails', 'advanced.sender': 'Expéditeur vérifié', 'advanced.supportEmail': 'E-mail d’assistance', 'advanced.instanceAdmin': 'Instance et administrateur', 'advanced.bootstrapAdmin': 'E-mail administrateur initial', 'advanced.localPort': 'Port local', 'advanced.networkPorts': 'Ports réseau', 'advanced.apiPort': 'Port API', 'advanced.uiPort': 'Port interface', 'advanced.randomPort': 'Trouver un port libre aléatoire', 'advanced.randomPorts': 'Trouver des ports libres aléatoires', 'advanced.otherDevices': 'Accès depuis d’autres appareils', 'advanced.sameWifiPrefix': 'Gardez les appareils sur le', 'advanced.sameWifi': 'même réseau Wi-Fi', 'advanced.firewall': 'Si demandé, autorisez HomeInventory ou Node.js dans le pare-feu Windows pour les réseaux privés.', 'advanced.findIp': 'Trouver votre IP : Réglages système → Wi-Fi → Détails → Adresse IP',
  'dev.console': 'Console de développement', 'dev.logs': 'Journaux', 'dev.backups': 'Sauvegardes', 'dev.settings': 'Paramètres', 'dev.updates': 'Mises à jour', 'dev.backupDescription': 'Sauvegardez vos données et médias locaux en un clic.', 'dev.backingUp': 'Sauvegarde...', 'dev.backupNow': 'Sauvegarder', 'dev.openBackup': 'Ouvrir la sauvegarde', 'dev.installFolder': 'Dossier d’installation', 'dev.installFolderHelp': 'Choisissez un dossier vide pour une nouvelle installation ou un dossier HomeInventory existant.', 'dev.nodePath': 'Chemin Node', 'dev.npmPath': 'Chemin npm', 'dev.autoDetected': 'Détecté automatiquement', 'dev.nodePathHelp': 'À définir uniquement si le launcher ne trouve pas votre installation Node.', 'dev.npmPathHelp': 'À définir uniquement si l’application de bureau ne détecte pas npm.', 'dev.openFolder': 'Ouvrir le dossier', 'dev.openData': 'Ouvrir les données', 'dev.resetDetection': 'Réinitialiser la détection Node/npm', 'dev.stopServer': 'Arrêter le serveur', 'dev.noLogs': 'Aucune entrée de journal.', 'dev.choosePath': 'Choisir le chemin', 'dev.openLocation': 'Ouvrir l’emplacement', 'dev.useDetectedPath': 'Utiliser le chemin détecté',
};

const es: Dictionary = { ...en,
  'qr.code': 'Código QR', 'qr.scan': 'Escanea para conectarte',
  'language.launcherLanguage': 'Idioma del launcher', 'language.savedHelp': 'Se aplica al instante y se recuerda en este dispositivo.',
  'status.existingInstance': 'HomeInventory ya se está ejecutando en los puertos seleccionados. Abre la sesión existente en lugar de iniciar otra.', 'status.apiPortBusy': 'El puerto API {port} está ocupado. Sugerencia: {suggested}.', 'status.uiPortBusy': 'El puerto de interfaz {port} está ocupado. Sugerencia: {suggested}.', 'status.bothPortsBusy': 'Los puertos {backend} y {frontend} están ocupados. Sugerencia: {suggestedBackend}/{suggestedFrontend}.', 'status.networkReady': 'La dirección de red está lista. Si otro dispositivo no puede conectarse, permite HomeInventory o Node.js en el Firewall de Windows para redes privadas.', 'status.lanUiBlocked': 'No se puede acceder a la interfaz mediante la IP de la LAN. Comprueba el Firewall de Windows y la vinculación de red.', 'status.lanApiBlocked': 'Se puede acceder a la interfaz, pero no a la API mediante la IP de la LAN.', 'status.lanBlocked': 'La comprobación de la LAN ha fallado. Permite HomeInventory o Node.js en el Firewall de Windows para redes privadas y reinicia la aplicación.',
  'update.stateStarting': 'Iniciando', 'update.stateBackingUp': 'Creando copia', 'update.stateDownloading': 'Descargando', 'update.stateInstalling': 'Instalando', 'update.stateCompleted': 'Completado', 'update.stateRollback': 'Revirtiendo', 'update.stateRollbackComplete': 'Reversión completada', 'update.stateFailed': 'Error',
  'language.en': 'English', 'language.tr': 'Türkçe', 'language.de': 'Deutsch', 'language.fr': 'Français', 'language.es': 'Español', 'common.launcher': 'Launcher', 'common.detected': 'Detectado: {path}',
  'status.launcherReady': 'El launcher está listo.', 'status.browserPreview': 'Vista previa del navegador — los comandos de Tauri se simulan.', 'status.loadingEnvironment': 'Cargando el entorno…', 'status.noProfile': 'No hay ningún perfil disponible.', 'status.apiPortRange': 'El puerto API debe estar entre 1024 y 65535.', 'status.uiPortRange': 'El puerto de interfaz debe estar entre 1024 y 65535.', 'status.localPortRange': 'El puerto local debe estar entre 1024 y 65535.', 'status.portsDifferent': 'Los puertos de API e interfaz deben ser diferentes.', 'status.portsAvailable': 'Los puertos están disponibles.', 'status.localPortValid': 'El puerto local es válido.', 'status.previewPortsValid': 'Los puertos parecen válidos en la vista previa del navegador.', 'status.checkingPorts': 'Comprobando los puertos locales antes de iniciar…', 'status.randomLocalPort': 'Se ha elegido el puerto local disponible {port}.', 'status.randomPorts': 'Se han elegido los puertos disponibles API/interfaz {backend}/{frontend}.', 'status.defaultPortsBusy': 'Los puertos predeterminados están ocupados. Iniciando en {backend}/{frontend}.', 'status.startPreview': 'Iniciando {name}: simulado en modo navegador.', 'status.stopPreview': 'Perfil activo detenido: simulado en modo navegador.', 'status.setupStopped': 'HomeInventory se detuvo antes de terminar de iniciarse. Abre las herramientas de desarrollo para ver los registros.', 'status.folderPickerDesktop': 'El selector de carpetas está disponible en el launcher de escritorio.', 'status.folderSelected': 'Carpeta de instalación seleccionada.', 'status.folderCleared': 'Carpeta de instalación borrada.', 'status.pathPickerDesktop': 'El selector de rutas está disponible en el launcher de escritorio.', 'status.pathUpdated': 'Ruta actualizada. La detección de herramientas se actualizará automáticamente.', 'status.pathEmpty': 'La ruta de {label} está vacía.', 'status.folderRevealDesktop': 'La función para mostrar carpetas está disponible en el launcher de escritorio.', 'status.pathOpened': 'Se ha abierto {label}.', 'status.nodeOverridesCleared': 'Se han borrado las rutas personalizadas de Node/npm. La detección automática está activa.', 'status.backupPreview': 'Copia creada para {name}: simulada en modo navegador.',
  'setup.elapsedBundled': 'Tiempo transcurrido: {elapsed}. Preparando los archivos incluidos y el entorno.', 'setup.elapsedInstall': 'Tiempo transcurrido: {elapsed}. La primera instalación puede tardar unos minutos según npm y la velocidad de la red.', 'setup.runtimeHelp': 'Inicia HomeInventory Local para preparar el entorno incluido en el paquete de Microsoft Store.', 'setup.nodeHelpPrefix': 'Descarga e instala Node.js desde', 'setup.nodeHelpSuffix': 'para continuar.', 'setup.launchOn': 'Iniciar en {backend}/{frontend}', 'setup.restartLocal': 'Reiniciar HomeInventory Local', 'setup.storePreparation': 'HomeInventory Local preparará los archivos incluidos y el entorno local del paquete de Microsoft Store.', 'setup.chooseFolderHelp': 'Elige una carpeta de instalación vacía o una carpeta de HomeInventory existente.', 'setup.emptyFolderSelected': 'Se ha seleccionado una carpeta vacía. HomeInventory se descargará e instalará aquí.', 'setup.invalidFolder': 'Esta carpeta no está vacía y no es una carpeta de instalación de HomeInventory.',
  'update.previousAvailable': 'La versión anterior sigue disponible. Inténtalo de nuevo cuando estés listo.', 'update.lookingForReleases': 'Buscando versiones firmadas del launcher y la aplicación.', 'update.nodeUpgradeBeforeInstall': 'Node.js debe actualizarse antes de instalar esta actualización.', 'update.installBeforeStart': 'Instala la actualización verificada antes de iniciar HomeInventory.', 'update.noneAvailable': 'No hay actualizaciones disponibles ahora.', 'update.verifyBeforeStart': 'Comprueba las versiones, firmas y requisitos antes de iniciar los servicios.', 'update.checkFirst': 'Busca actualizaciones antes de iniciar la actualización.', 'update.noInstallAvailable': 'Tu software está actualizado. No hay ninguna actualización para instalar.', 'update.initializing': 'Preparando la actualización...', 'update.backingUp': 'Creando copia de la base de datos y los archivos...', 'update.downloading': 'Descargando el archivo de la versión...', 'update.installing': 'Instalando dependencias con npm ci...', 'update.complete': '¡Actualización completada!', 'update.toVersion': '(Actualizar a v{version})', 'update.nodeRequiredBody': 'La última versión de la aplicación requiere Node.js v{version} o posterior. Actualiza tu entorno de Node.js para continuar.', 'update.checkExplanation': 'Antes de actualizar, el launcher debe comprobar la última versión, las firmas, la versión de Node.js necesaria y las actualizaciones disponibles de la aplicación o el launcher.',
  'https.ios': 'iPhone / iPad', 'https.android': 'Android', 'https.optionalLabel': 'Acceso seguro opcional a la cámara móvil', 'https.startFirst': 'Inicia HomeInventory antes de activar el acceso seguro a la cámara móvil.', 'https.previewEnabled': 'La configuración segura de la cámara móvil se simula en la vista previa del navegador.', 'https.readyNotice': 'El acceso móvil seguro está listo en {url}. Instala la CA local en cada teléfono antes de abrirlo.', 'https.disabledNotice': 'El acceso móvil seguro está desactivado. El acceso HTTP normal no ha cambiado.', 'https.rotateConfirm': '¿Renovar la CA local de HomeInventory? Todos los teléfonos registrados dejarán de confiar en el certificado anterior y deberán instalar el nuevo.', 'https.rotatePreview': 'La renovación de la CA local se simula en la vista previa del navegador.',
  'android.samsung': 'Samsung Galaxy',
  'advanced.emailHelp': 'Resend necesita una clave API y una dirección de remitente verificada. Una clave por sí sola puede parecer configurada aunque falle la entrega.', 'advanced.adminHelp': 'El correo de administrador inicial permite definir claramente el primer administrador de confianza.', 'advanced.networkStore': 'HomeInventory Local utiliza un puerto local para la aplicación y la API.', 'advanced.networkDesktop': 'Los puertos deben estar libres localmente; el acceso LAN también depende del cortafuegos y de usar la misma red Wi-Fi.', 'advanced.resendKey': 'Clave API de Resend', 'advanced.resendHelp': 'Activa las invitaciones, la verificación, el correo de administración y los mensajes de restablecimiento de contraseña.', 'advanced.senderHelp': 'Usa un remitente de un dominio verificado en Resend. Para pruebas rápidas, Resend permite onboarding@resend.dev.', 'advanced.supportHelp': 'Se muestra en los enlaces de ayuda y en el pie de los correos enviados.', 'advanced.bootstrapHelp': 'La cuenta coincidente recibe permisos de administrador durante la primera configuración o inicio de sesión.', 'advanced.envHelp': 'El launcher solo escribe en .env los valores completados, por lo que se conserva la configuración existente.', 'advanced.storePortHelp': 'Intervalo válido: 1024–65535. Predeterminado: 3001. Cámbialo solo si otra aplicación usa el mismo puerto.', 'advanced.desktopPortHelp': 'Intervalo válido: 1024–65535. Predeterminados: API 3001, interfaz 5173. Cámbialos solo si otra aplicación usa los mismos puertos.', 'advanced.usePort': 'Usar {port}', 'advanced.usePorts': 'Usar {backend}/{frontend}',
  'language.label': 'Idioma', 'common.close': 'Cerrar', 'common.clear': 'Borrar', 'common.required': 'Obligatorio', 'common.recommended': 'Recomendado', 'common.ready': 'Listo', 'common.offline': 'Sin conexión', 'common.checkAgain': 'Comprobar de nuevo', 'common.checking': 'Comprobando…', 'common.managedApp': 'Aplicación gestionada',
  'setup.subtitle': 'Tu inventario doméstico privado', 'setup.localFirst': 'Local primero', 'setup.waiting': 'Esperando para iniciar…', 'setup.nodeRequired': 'Se requiere Node.js.', 'setup.preparingFiles': 'Preparando los archivos de la aplicación…', 'setup.installing': 'Instalando dependencias y preparando la aplicación…', 'setup.failed': 'La configuración se detuvo tras un error. Elige otra carpeta de instalación e inténtalo de nuevo.', 'setup.runtimeNotReady': 'El entorno incluido no está listo', 'setup.nodeNotFound': 'No se encontró Node.js', 'setup.checkingLocalPorts': 'Comprobando puertos locales…', 'setup.launchLocal': 'Iniciar HomeInventory Local', 'setup.chooseInstallFolder': 'Elegir carpeta de instalación', 'setup.installLaunch': 'Instalar e iniciar', 'setup.openRunning': 'Abrir HomeInventory en ejecución', 'setup.initializeLaunch': 'Inicializar e iniciar', 'setup.developerTools': 'Herramientas de desarrollo', 'setup.hideConsole': 'Ocultar consola', 'setup.systemConsole': 'Consola del sistema', 'setup.connectingRegistry': 'Conectando con tu inventario', 'setup.startingServices': 'Iniciando servicios…', 'setup.launching': 'Iniciando…', 'setup.connectingDatabase': 'Conectando con la base de datos…', 'setup.servicesStopped': 'Los servicios están detenidos', 'setup.readyToLaunch': 'Listo para iniciar', 'setup.restart': 'Reiniciar HomeInventory', 'setup.launch': 'Iniciar HomeInventory', 'setup.checkingUpdates': 'Buscando actualizaciones…', 'setup.updateApp': 'Actualizar la aplicación a v{version}',
  'update.kicker': 'Actualizaciones', 'update.syncPaused': 'Sincronización de la aplicación gestionada en pausa', 'update.inProgress': 'Actualización en curso', 'update.checking': 'Buscando actualizaciones...', 'update.availableBeforeLaunch': 'Actualización disponible antes de iniciar', 'update.checkedBeforeLaunch': 'Comprobado antes de iniciar', 'update.checkBeforeLaunch': 'Buscar actualizaciones antes de iniciar', 'update.retrySync': 'Reintentar sincronización', 'update.updateFirst': 'Actualizar primero', 'update.checkUpdates': 'Buscar actualizaciones', 'update.checkForUpdates': 'Buscar actualizaciones', 'update.upToDateNotice': 'Tu software está actualizado.', 'update.manage': 'Gestiona y busca actualizaciones de software.', 'update.checkingForUpdates': 'Buscando actualizaciones...', 'update.nodeRequired': 'Se requiere actualizar Node.js', 'update.appReleaseNotes': 'Notas de la aplicación', 'update.launcherReleaseNotes': 'Notas del launcher', 'update.softwareCurrent': 'Tu software está actualizado', 'update.latestVersions': 'Estás usando la última versión de HomeInventory y del launcher de escritorio.', 'update.updateHomeInventory': 'Actualizar HomeInventory', 'update.checkBeforeInstalling': 'Buscar actualizaciones antes de instalar', 'update.temporarilyUnavailable': 'La información de actualización no está disponible temporalmente',
  'running.status': 'En ejecución', 'running.localAccess': 'Acceso local', 'running.ready': 'Tu inventario está listo.', 'running.help': 'Ábrelo en este dispositivo o escanea el código desde otro dispositivo de la misma red.', 'running.standardLan': 'Acceso LAN estándar · sin configurar certificado', 'running.lanPending': 'El estado de la LAN se comprueba cuando los servicios se conectan a la red.', 'running.openBrowser': 'Abrir en el navegador', 'running.openApp': 'Abrir aplicación', 'running.port': 'Puerto {port}', 'running.ports': 'Puertos {backend}/{frontend}', 'running.controls': 'Controles de la aplicación', 'running.settings': 'Ajustes del launcher', 'running.stop': 'Detener servicios locales', 'running.active': '{name} está en ejecución.',
  'https.setupLabel': 'Configuración segura de la cámara móvil', 'https.title': 'Acceso seguro a la cámara móvil', 'https.subtitle': 'Opcional · sin conexión · sin dominio ni servicio externo', 'https.installTitle': '1 · Instala el certificado', 'https.choosePlatform': 'Elige iPhone / iPad o Android.', 'https.iosHelp': 'Instala el perfil y activa la confianza total en Ajustes → General → Información → Ajustes de confianza de certificados.', 'https.downloadPrefix': 'El QR descarga', 'https.downloadSuffix': 'el certificado de CA público generado para este launcher. No contiene claves privadas ni datos de HomeInventory.', 'https.phoneBrand': 'Marca del teléfono', 'https.scanDownload': 'Escanea el QR para descargar el certificado.', 'https.typicalPath': 'Ruta habitual:', 'https.finishInstall': 'Selecciona el archivo descargado, termina la instalación y después escanea', 'https.openSecureApp': '2 · Abrir la aplicación segura', 'https.menuVariation': 'Los nombres de los menús pueden variar ligeramente según la versión de Android.', 'https.secureHelp': 'El navegador debe abrir esta dirección sin avisos de certificado para que funcione el permiso de cámara.', 'https.linksExpire': 'Los enlaces de configuración caducan tras 10 minutos. La clave privada de la CA nunca sale de este ordenador.', 'https.refreshLinks': 'Actualizar enlaces de configuración', 'https.disable': 'Desactivar HTTPS', 'https.rotate': 'Renovar CA comprometida', 'https.removal': 'Desactivar HTTPS no elimina la CA de confianza del teléfono. Elimina el perfil o la CA de HomeInventory en los ajustes cuando ya no se necesite.', 'https.wantCamera': '¿Quieres escanear con la cámara del teléfono?', 'https.oneTimeSetup': 'El acceso a la cámara por LAN requiere una configuración HTTPS de confianza una vez en cada teléfono.', 'https.enable': 'Activar cámara móvil segura', 'https.normalRemains': 'El acceso HTTP normal seguirá disponible y esta configuración es totalmente opcional.',
  'android.pixel': 'Google Pixel / Android estándar', 'android.other': 'Otro Android', 'android.samsungPath': 'Ajustes → Seguridad y privacidad → Más ajustes de seguridad → Instalar desde almacenamiento del dispositivo → Certificado de CA', 'android.pixelPath': 'Ajustes → Seguridad y privacidad → Más ajustes de seguridad → Cifrado y credenciales → Instalar un certificado → Certificado de CA', 'android.otherPath': 'Abre Ajustes, busca «Instalar certificado» y elige Certificado de CA.',
  'advanced.title': 'Avanzado', 'advanced.configuration': 'Configuración avanzada', 'advanced.whatMatters': 'Lo importante aquí', 'advanced.emailLabel': 'Correo:', 'advanced.adminLabel': 'Administrador:', 'advanced.networkLabel': 'Red:', 'advanced.emailDelivery': 'Entrega de correo', 'advanced.sender': 'Remitente verificado', 'advanced.supportEmail': 'Correo de soporte', 'advanced.instanceAdmin': 'Instancia y administrador', 'advanced.bootstrapAdmin': 'Correo de administrador inicial', 'advanced.localPort': 'Puerto local', 'advanced.networkPorts': 'Puertos de red', 'advanced.apiPort': 'Puerto API', 'advanced.uiPort': 'Puerto de interfaz', 'advanced.randomPort': 'Buscar un puerto libre aleatorio', 'advanced.randomPorts': 'Buscar puertos libres aleatorios', 'advanced.otherDevices': 'Acceso desde otros dispositivos', 'advanced.sameWifiPrefix': 'Mantén los dispositivos en la', 'advanced.sameWifi': 'misma red Wi-Fi', 'advanced.firewall': 'Si se solicita, permite HomeInventory o Node.js en el Firewall de Windows para redes privadas.', 'advanced.findIp': 'Busca tu IP: Ajustes del sistema → Wi-Fi → Detalles → Dirección IP',
  'dev.console': 'Consola de desarrollo', 'dev.logs': 'Registros', 'dev.backups': 'Copias de seguridad', 'dev.settings': 'Ajustes', 'dev.updates': 'Actualizaciones', 'dev.backupDescription': 'Copias de tus datos y archivos locales con un clic.', 'dev.backingUp': 'Creando copia...', 'dev.backupNow': 'Crear copia ahora', 'dev.openBackup': 'Abrir copia', 'dev.installFolder': 'Carpeta de instalación', 'dev.installFolderHelp': 'Elige una carpeta vacía para una instalación nueva o una carpeta de HomeInventory existente.', 'dev.nodePath': 'Ruta de Node', 'dev.npmPath': 'Ruta de npm', 'dev.autoDetected': 'Detectado automáticamente', 'dev.nodePathHelp': 'Configúralo solo si el launcher no encuentra tu instalación de Node.', 'dev.npmPathHelp': 'Configúralo solo si la aplicación de escritorio no detecta npm.', 'dev.openFolder': 'Abrir carpeta', 'dev.openData': 'Abrir datos', 'dev.resetDetection': 'Restablecer detección de Node/npm', 'dev.stopServer': 'Detener servidor', 'dev.noLogs': 'Aún no hay registros.', 'dev.choosePath': 'Elegir ruta', 'dev.openLocation': 'Abrir ubicación', 'dev.useDetectedPath': 'Usar ruta detectada automáticamente',
};

const dictionaries: Record<LauncherLocale, Dictionary> = { en, tr, de, fr, es };
const STORAGE_KEY = 'homeinventory-launcher-language';

export const LANGUAGE_OPTIONS: ReadonlyArray<{ code: LauncherLocale; labelKey: TranslationKey }> = [
  { code: 'en', labelKey: 'language.en' },
  { code: 'tr', labelKey: 'language.tr' },
  { code: 'de', labelKey: 'language.de' },
  { code: 'fr', labelKey: 'language.fr' },
  { code: 'es', labelKey: 'language.es' },
];

function resolveLocale(value: string | null | undefined): LauncherLocale | null {
  if (!value) return null;
  const normalized = value.toLowerCase().split('-')[0];
  return normalized === 'en' || normalized === 'tr' || normalized === 'de' || normalized === 'fr' || normalized === 'es'
    ? normalized
    : null;
}

function initialLocale(): LauncherLocale {
  try {
    const stored = resolveLocale(localStorage.getItem(STORAGE_KEY));
    if (stored) return stored;
  } catch { /* localStorage can be unavailable in hardened webviews */ }
  for (const language of navigator.languages || [navigator.language]) {
    const resolved = resolveLocale(language);
    if (resolved) return resolved;
  }
  return 'en';
}

export type Translate = (key: TranslationKey, variables?: Variables) => string;

type I18nValue = {
  locale: LauncherLocale;
  setLocale: (locale: LauncherLocale) => void;
  t: Translate;
};

const I18nContext = createContext<I18nValue | null>(null);

export function LauncherI18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<LauncherLocale>(initialLocale);
  const setLocale = useCallback((next: LauncherLocale) => {
    setLocaleState(next);
    try { localStorage.setItem(STORAGE_KEY, next); } catch { /* preference remains in memory */ }
  }, []);
  const t = useCallback<Translate>((key, variables) => {
    let message = dictionaries[locale][key] || en[key];
    if (variables) {
      for (const [name, value] of Object.entries(variables)) {
        message = message.split(`{${name}}`).join(String(value));
      }
    }
    return message;
  }, [locale]);

  useEffect(() => {
    document.documentElement.lang = locale;
  }, [locale]);

  const value = useMemo(() => ({ locale, setLocale, t }), [locale, setLocale, t]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useLauncherI18n() {
  const value = useContext(I18nContext);
  if (!value) throw new Error('useLauncherI18n must be used inside LauncherI18nProvider');
  return value;
}

export const launcherDictionaries = dictionaries;
